openapi: 3.0.0
info:
  title: Place API
  description: API for managing places (vietos) in a system
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
paths:
  /vietos:
    get:
      summary: Get all places
      description: Retrieve a list of all places in the system.
      responses:
        '200':
          description: A list of places
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Place'
              
  /vieta/{id}:
    get:
      summary: Get a place by ID
      description: Retrieve a specific place by its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: The ID of the place to retrieve.
      responses:
        '200':
          description: A specific place
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
        '404':
          description: Place not found

    put:
      summary: Update a place by ID
      description: Update the details of an existing place.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: The ID of the place to update.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Place'
      responses:
        '200':
          description: Place updated successfully
        '404':
          description: Place not found

    delete:
      summary: Delete a place by ID
      description: Delete a specific place by its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: The ID of the place to delete.
      responses:
        '204':
          description: Place deleted successfully
        '404':
          description: Place not found

  /vieta:
    post:
      summary: Create a new place
      description: Add a new place to the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Place'
      responses:
        '201':
          description: Place created successfully
        '400':
          description: Missing or invalid parameters
        '409':
          description: A place with the given ID already exists

components:
  schemas:
    Place:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Central Park
        address:
          type: string
          example: "123 Main Street"
        city:
          type: string
          example: New York
        postal_code:
          type: string
          example: "10001"
        country:
          type: string
          example: USA
        capacity:
          type: integer
          example: 1000
      required:
        - name
        - address
        - city
        - postal_code
        - country
        - capacity